import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/src/components/ui/tooltip";
import { CartProvider } from "@/src/context/cart-context";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Karma Dhuen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "dark",
        "font-sans",
        inter.variable
      )}
    >
      <body className="min-h-full flex flex-col">
        <TooltipProvider>
          <CartProvider>{children}</CartProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}